/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.1.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("com.diffplug.spotless") version "6.25.0"
    id("com.github.johnrengelman.shadow") version "8.1.1"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // This dependency is used by the application.
    implementation(libs.guava)
    // WebSocket support
    implementation("org.java-websocket:Java-WebSocket:1.5.4")
    // JSON support
    implementation("org.json:json:20240303")
    // Prometheus metrics instrumentation
    implementation("io.micrometer:micrometer-core:1.13.0")
    implementation("io.micrometer:micrometer-registry-prometheus:1.13.0")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.example.App"
}

tasks.named<JavaExec>("run") {
    // Set working directory to project root so config.properties can be found
    workingDir = rootProject.projectDir
}

spotless {
    java {
        eclipse().configFile("${project.rootDir}/eclipse-formatter.xml")
        removeUnusedImports()
        trimTrailingWhitespace()
        endWithNewline()
    }
}

// Configure shadow jar to create fat JAR with all dependencies
tasks.named<com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar>("shadowJar") {
    archiveClassifier.set("")
    manifest {
        attributes(mapOf("Main-Class" to "org.example.App"))
    }
}

// Disable application plugin distribution tasks since we use shadowJar
tasks.named("startScripts") {
    enabled = false
}

tasks.named("distTar") {
    enabled = false
}

tasks.named("distZip") {
    enabled = false
}

// Disable regular jar since we use shadowJar
tasks.jar {
    enabled = false
}

// Make build depend on shadowJar
tasks.build {
    dependsOn(tasks.shadowJar)
}
